### ISSUE TITLE
Conflict with WordPress SEO by Yoast plugin (Undefined property: WP_Query::$post error)

### ISSUE THREAD

**Issue by hadi060** [f4bsch/WP-Filebase#8]
Hi.
I'm using WP-Filebase Download Manager plugin to manage downloads on my website. It displays download link automatically at the end of the post, but when I install WordPress SEO by Yoast plugin the download link disappears!
I'v posted a thread a year ago at WP-Filebase Download support forum here:
https://wordpress.org/support/topic/show-attached-files-is-not-working
Other persons seem to have the same issue, but no answer from the plugin's author.
I'v also reposted a thread 4 months ago at WordPress SEO by Yoast support forum without answer:
https://wordpress.org/support/topic/conflict-with-wp-filebase-download-manager
After posting this issue here:
https://github.com/Yoast/wordpress-seo/issues/1911
Yoast asked me to enable `WP_DEBUG` to see if there is any errors. After do that, I'v seen this notice:
`Notice: Undefined property: WP_Query::$post in .../wp-includes/query.php on line 3960`
and it's displayed just when WP-Filebase Download Manager plugin is activated, so I think the problem comes from it.
Hope you find a solution to this problem.
Thank you.

**Comment by joshhowenstine** [comment]
What version of the plugin are you currently using. I had a conflict with Yoast SEO earlier last month. However it has since be fixed in the recent versions.

**Comment by hadi060** [comment]
Thanks Josh for your reply.
I'm using the latest version (0.3.0.06). It's a new website so all plugins are up to date.

**Comment by joshhowenstine** [comment]
Do you have a link where I can view how you are using filebase. Maybe I can recreate the error on my dev server and figure out where the conflict is.

**Comment by hadi060** [comment]
I'm using it on a new arabic website. Do you mean you want admin access to my wordpress?
I think you can just try to install a fresh wordpress on your dev server, then install both plugins (WP-Filebase and Yoast SEO), then try to create a new post with a file uploaded via WP-Filebase, I think the link will be absent is this case until you deactivate the SEO plugin. It is not the first time I'm facing this problem.

**Comment by joshhowenstine** [comment]
Yeah don't need admin access or anything, will see if I can reproduce.

**Comment by hadi060** [comment]
the link is: http://www.tilmide.com
It's still not live using maintenance mode plugin. Do you want to make it live for you? Also it's still with the default theme.

**Comment by joshhowenstine** [comment]
Hit me up direct at the email address on my profile. Then we can post back here for 
Fabian if we find a solution.

**Comment by hadi060** [comment]
Do you want me to send you admin access by email? Sorry if I can't understand what you mean because I'm not enough good at English :)

**Comment by joshhowenstine** [comment]
No problem. No, I just figured we could go back and forth via email for a bit and keep the chatter off gitbub for awhile until we found a resolution to your issue.

**Comment by hadi060** [comment]
Do you mean we can continue resolving this problem via email?

**Comment by joshhowenstine** [comment]
Correct.

**Comment by f4bsch** [comment]
You should try update 3.1.00 I just pushed. 
WP SEO generates the post content 2 times, first for keyword indexing, and then the real content for displaying. WP-Filebase was assuming that the attached files where already rendered after the keyword indexing and thus did not generate the code again.

The trick was to check if scripts where already printed ( ``did_action('wp_print_scripts')`` )

**Comment by hadi060** [comment]
Thank you very much for your reply Fabian, and thanks for fixing the issue. When will this update be live on wordpress.org?

**Comment by hadi060** [comment]
Thank you for the fix. It's working. I'v installed the latest version by downloading it from github, after waiting a while for it to be live on wordpress.org, but it's still not there.
Thanks again.

**Comment by f4bsch** [comment]
I've just commited it to wordpress.org
